### ISSUE TITLE
default cookiecutter log directory path should be generic

### ISSUE THREAD

**Issue by JoshKarpel** [Snakemake-Profiles/htcondor#4]
The cookiecutter template uses a log directory path that points to a directory on the author's computer:

https://github.com/Snakemake-Profiles/htcondor/blob/e9b911be339f1bd9318d7d0a9d2a6bb3d870c7f5/cookiecutter.json#L3

I'm not sure what kind of interpolation is available where this value is used (https://github.com/Snakemake-Profiles/htcondor/blob/master/%7B%7Bcookiecutter.profile_name%7D%7D/grid-submit.py#L16), but perhaps the path could be relative to the directory the `Snakefile` is in? `<snakefile_dir>/htcondor_logs`, or similar? If not, perhaps relative to the user's home directory?

**Comment by jheuel** [comment]
Thanks for looking through the code! I agree that the path could be more generic, as it is just a placeholder that users need to adjust to their setup. However, in most cases it might be not the best idea to set this log file directory to somewhere in the users home directory, because the quota for home directories is usually quite small, while some form of extra storage for job outputs and logs is present (like here the /net stuff).

**Comment by JoshKarpel** [comment]
Hmmm. Good point on the home directory - different clusters vary a lot in how they have that set up.

I wonder if instead of an absolute path, it could just be a plain relative path. Since the path is constructed by path joining in `grid-submit.py`, it would then be relative to where `snakemake` was run from (I assume; I'm not very familiar with `snakemake` yet).
